const countryesSet = [
    {
        country: 'Great Britain',
        counrtyRU: 'Великобритания',
        countryBY: '',
        countryShort: 'GB',
        capital: 'London',
        capitalRU: 'Лондон',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'France',
        counrtyRU: 'Франция',
        countryBY: '',
        countryShort: 'FR',
        capital: 'Paris',
        capitalRU: 'Париж',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Itali',
        counrtyRU: 'Италия',
        countryBY: '',
        countryShort: 'IT',
        capital: 'Roma',
        capitalRU: 'Рим',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Ukraine',
        counrtyRU: 'Украина',
        countryBY: '',
        countryShort: 'UA',
        capital: 'Kiev',
        capitalRU: 'Киев',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Germany',
        counrtyRU: 'Германия',
        countryBY: '',
        countryShort: 'DE',
        capital: 'Berlin',
        capitalRU: 'Берлин',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Czech Republic',
        counrtyRU: 'Чехия',
        countryBY: '',
        countryShort: 'CZ',
        capital: 'Prague',
        capitalRU: 'Прага',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Austria',
        counrtyRU: 'Австрия',
        countryBY: '',
        countryShort: 'AT',
        capital: 'Vien',
        capitalRU: 'Вена',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Spain',
        counrtyRU: 'Испания',
        countryBY: '',
        countryShort: 'ES',
        capital: 'Madrid',
        capitalRU: 'Мадрид',
        capitalBY: '',
        about:
            'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas obcaecati officia earum nemo veritatis ullam modi pariatur impedit sint aut optio doloremque laudantium ex excepturi sed temporibus consequuntur nihil, accusantium dolorem quam nam placeat ipsam. Obcaecati qui enim non veritatis molestiae cumque similique sapiente corporis sint quas eligendi quibusdam, laudantium itaque minus vero omnis corrupti, quaerat dolorem temporibus architecto impedit. Autem, sed aliquid? Beatae, provident? Quidem tempore voluptatem consectetur neque, dignissimos beatae quod itaque rem optio. Deleniti rem eligendi maiores incidunt aspernatur eum magni, beatae quasi nisi? Labore culpa recusandae at, porro nam ea. Obcaecati atque quos magni quas hic!',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        imagesDiscr: ['', '', '', '', '', ''],
        imagesDiscrRU: ['', '', '', '', '', ''],
        imagesDiscrBY: ['', '', '', '', '', ''],
        currency: '',
    },
];

export default countryesSet;
