const countryesSet = [
    {
        country: 'Great Britain',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'GB',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'France',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'FR',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Itali',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'IT',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Ukraine',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'UA',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Germany',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'DE',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Czech Republic',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'CZ',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Austria',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'AT',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
    {
        country: 'Spain',
        counrtyRU: '',
        countryBY: '',
        countryShort: 'ES',
        capital: '',
        capitalEN: '',
        capitalBY: '',
        about: '',
        aboutRU: '',
        aboutBY: '',
        videoLink: '',
        timeZone: 0,
        images: ['', '', '', '', '', ''],
        currency: '',
    },
];

export default countryesSet;
